import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/containers/containers.css";
import "@/styles/components/inputs.css";
import { Header } from "@/components/layout/Header/Header";
import { QueryProvider } from "@/components/providers/QueryProvider/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={inter.className}>
          <Header />
          <main className="main">{children}</main>
        </body>
      </QueryProvider>
    </html>
  );
}
